name: warden
channel: fast
version: v0.5.1
defaultCR: config/samples/default_serverless_cr.yaml
manifest: serverless-operator.yaml
security: sec-scanners-config.yaml
annotations:
  "operator.kyma-project.io/doc-url": "https://kyma-project.io/#/serverless-manager/user/README"
moduleRepo: https://github.com/kyma-project/serverless-manager.git
