name: kyma-project.io/module/warden
version:
manifest: warden.yaml
repository: https://github.com/kyma-project/warden.git
mandatory: true
security: sec-scanners-config.yaml
manager:
  name: warden-operator
  group: apps
  version: v1
  kind: Deployment
icons:
  - name: module-icon
    # TODO: provide warden icon
    link: https://raw.githubusercontent.com/kyma-project/kyma/refs/heads/main/docs/assets/logo_icon.svg