apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.global.name }}
    kyma-project.io/module: {{ .Values.global.name }}
    app.kubernetes.io/name: {{ .Values.global.name }}
    app.kubernetes.io/instance: {{ .Chart.Name }}-deployment
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: {{ .Chart.Name }}
    app.kubernetes.io/part-of: {{ .Values.global.name }}
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app: {{ .Values.global.name }}
      app.kubernetes.io/part-of: {{ .Values.global.name }}
      app.kubernetes.io/component: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.name }}
        kyma-project.io/module: {{ .Values.global.name }}
        app.kubernetes.io/name: {{ .Values.global.name }}
        app.kubernetes.io/instance: {{ .Values.global.name }}-{{ .Chart.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/component: {{ .Chart.Name }}
        app.kubernetes.io/part-of: {{ .Values.global.name }}
        app.kubernetes.io/managed-by: Helm
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: {{ .Chart.Name }}
      containers:
        - name: admission
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          imagePullPolicy: IfNotPresent
          image: "{{ .Values.global.admission.image }}"
          readinessProbe:
            httpGet:
              port: 8090
              path: /readyz/
          resources:
            {{- toYaml .Values.global.admission.resources | nindent 12 }}
          args:
            - --config-path={{- .Values.global.config.dir }}/{{- .Values.global.config.filename }}
          env:
            - name: ADDMISSION_ADD_CERT_OWNER_REF
              value: "true"
            - name: ADMISSION_DEPLOYMENT_NAME
              value: {{ .Chart.Name }}
          ports:
            - name: https-admission
              containerPort: 8443
            - name: http-metrics
              containerPort: 9090
            - name: http-profiling
              containerPort: 8008
            - name: health
              containerPort: 8090
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: {{ .Values.global.config.dir }}
            - name: tmp-cert
              mountPath: /tmp/k8s-webhook-server/
            - name: notary-tmp
              mountPath: /tmp/.notary
      volumes:
        - name: config
          configMap:
            name: {{ .Values.global.config.configmapName }}
        - name: tmp-cert
          emptyDir: { }
        - name: notary-tmp
          emptyDir: { }
      priorityClassName: {{ .Values.global.wardenPriorityClassName }}
