apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.global.name }}
    kyma-project.io/module: {{ .Values.global.name }}
    app.kubernetes.io/name: {{ .Values.global.name }}
    app.kubernetes.io/instance: {{ .Chart.Name }}-service
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: {{ .Chart.Name }}
    app.kubernetes.io/part-of: {{ .Values.global.name }}
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - name: https-admission
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: {{ .Values.global.name }}
    app.kubernetes.io/part-of: {{ .Values.global.name }}
    app.kubernetes.io/component: {{ .Chart.Name }}
