apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.global.wardenPriorityClassName }}
  labels:
    kyma-project.io/module: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Chart.Name }}-priority-class
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: {{ .Chart.Name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: Helm
value: {{ .Values.global.wardenPriorityClassValue }}
globalDefault: false
description: "Scheduling priority of warden workloads. By default, warden workloads should not be blocked by unschedulable user workloads."
