apiVersion: v1
kind: Service
metadata:
  labels:
    app: warden
  name: {{ include "warden.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: https
  selector:
    app: warden
