apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.global.name }}
    kyma-project.io/module: {{ .Values.global.name }}
    app.kubernetes.io/name: {{ .Values.global.name }}
    app.kubernetes.io/instance: {{ .Chart.Name }}-deployment
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: {{ .Chart.Name }}
    app.kubernetes.io/part-of: {{ .Values.global.name }}
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.name }}
      app.kubernetes.io/part-of: {{ .Values.global.name }}
      app.kubernetes.io/component: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.name }}
        kyma-project.io/module: {{ .Values.global.name }}
        app.kubernetes.io/name: {{ .Values.global.name }}
        app.kubernetes.io/instance: {{ .Chart.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/component: {{ .Chart.Name }}
        app.kubernetes.io/part-of: {{ .Values.global.name }}
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: {{ .Chart.Name }}
      containers:
        - name: operator
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          image: "{{ .Values.global.operator.image }}"
          imagePullPolicy: IfNotPresent
          resources:
            {{- toYaml .Values.global.operator.resources | nindent 12 }}
          args:
            - --config-path={{- .Values.global.config.dir }}/{{- .Values.global.config.filename }}
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
          volumeMounts:
            - name: config
              mountPath: {{ .Values.global.config.dir }}
            - name: notary-tmp
              mountPath: /tmp/.notary
      volumes:
        - name: config
          configMap:
            name: {{ .Values.global.config.configmapName }}
        - name: notary-tmp
          emptyDir: { }
      priorityClassName: {{ .Values.global.wardenPriorityClassName }}
