apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.global.name }}
    kyma-project.io/module: {{ .Values.global.name }}
    app.kubernetes.io/name: {{ .Values.global.name }}
    app.kubernetes.io/instance: {{ .Chart.Name }}-serviceaccount
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/component: {{ .Chart.Name }}
    app.kubernetes.io/part-of: {{ .Values.global.name }}
    app.kubernetes.io/managed-by: Helm
