{{ if .Values.global.enableDeployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.global.name }}
    app.kubernetes.io/part-of: {{ .Values.global.name }}
    app.kubernetes.io/component: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.name }}
      app.kubernetes.io/part-of: {{ .Values.global.name }}
      app.kubernetes.io/component: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.name }}
        app.kubernetes.io/part-of: {{ .Values.global.name }}
        app.kubernetes.io/component: {{ .Chart.Name }}
      annotations:
        sidecar.istio.io/inject: "false" #TODO Copied from admission webhook deployment
    spec:
      serviceAccountName: {{ .Chart.Name }}
      containers:
        - name: admission
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          imagePullPolicy: IfNotPresent
          image: "{{ .Values.global.admission.image }}"
          resources:
            {{- toYaml .Values.global.admission.resources | nindent 12 }}
          args:
            - --config-path={{- .Values.global.config.dir }}/{{- .Values.global.config.filename }}
          ports:
            - name: https-admission
              containerPort: 8443
            - name: http-metrics
              containerPort: 9090
            - name: http-profiling
              containerPort: 8008
          volumeMounts:
            - name: config
              mountPath: {{ .Values.global.config.dir }}
            - name: certs
              mountPath: /tmp/k8s-webhook-server/serving-certs
        - name: operator
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          image: "{{ .Values.global.operator.image }}"
          imagePullPolicy: IfNotPresent
          resources:
            {{- toYaml .Values.global.operator.resources | nindent 12 }}
          args:
            - --config-path={{- .Values.global.config.dir }}/{{- .Values.global.config.filename }}
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
          volumeMounts:
            - name: config
              mountPath: {{ .Values.global.config.dir }}
      volumes:
        - name: config
          configMap:
            name: {{ .Values.global.config.configmapName }}
        - name: certs
          secret:
            secretName: {{ .Chart.Name }}-cert
      priorityClassName: {{ .Values.global.wardenPriorityClassName }}
  {{ end }}
