# this stub is created to allow the reconciler to track this/these resource(s). It should not be deleted. The actual content of this resource and managed and reconciled by the function-webhook.
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.webhook.warden.kyma-project.io
  labels:
    app: {{ .Values.global.name }}
webhooks:
  - clientConfig:
      service:
        name: {{ .Chart.Name }}
        namespace: {{ .Release.Namespace }}
    failurePolicy: Ignore
    sideEffects: None
    matchPolicy: Exact
    timeoutSeconds: 15
    admissionReviewVersions: [ "v1beta1", "v1" ]
    name: validation.webhook.serverless.kyma-project.io
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: defaulting.webhook.warden.kyma-project.io
  labels:
    app: {{ .Values.global.name }}
webhooks:
  - clientConfig:
      service:
        name: {{ .Chart.Name }}
        namespace: {{ .Release.Namespace }}
    failurePolicy: Ignore
    sideEffects: None
    matchPolicy: Exact
    timeoutSeconds: 15
    admissionReviewVersions: [ "v1beta1", "v1" ]
    name: defaulting.webhook.warden.kyma-project.io
