// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	"context"
	mock "github.com/stretchr/testify/mock"
)

// ImageValidatorService is an autogenerated mock type for the ImageValidatorService type
type ImageValidatorService struct {
	mock.Mock
}

func (_m *ImageValidatorService) Validate2(ctx context.Context, image string) error {
	//TODO implement me
	panic("implement me")
}

// Validate provides a mock function with given fields: image
func (_m *ImageValidatorService) Validate(image string) error {
	ret := _m.Called(image)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(image)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewImageValidatorService interface {
	mock.TestingT
	Cleanup(func())
}

// NewImageValidatorService creates a new instance of ImageValidatorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewImageValidatorService(t mockConstructorTestingTNewImageValidatorService) *ImageValidatorService {
	mock := &ImageValidatorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
